import inspect
from pathlib import Path
import valency_anndata.tools as tools

# This file is a helper to ensure IDE hints match runtime docstrings
# on methods we modify while re-exporting from scanpy.

TOOLS_PY = Path("src/valency_anndata/tools/__init__.py")
TOOLS_PYI = Path("src/valency_anndata/tools/__init__.pyi")

# Ensure __all__ exists
exports = getattr(tools, "__all__", [])

lines = [
    "# ------------------------------------------------------",
    "# THIS FILE IS AUTO-GENERATED BY scripts/generate_ide_docstring_hints.py",
    f"# Source module: {TOOLS_PY}",
    "# DO NOT EDIT MANUALLY",
    "# ------------------------------------------------------",
    "",
    "from typing import Any",
    "",
    f"__all__ = {exports!r}",
    "",
]

for name in exports:
    obj = getattr(tools, name, None)
    if obj is None:
        lines.append(f"{name}: Any")
        continue

    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        try:
            sig = str(inspect.signature(obj))
        except ValueError:
            sig = "(*args: Any, **kwargs: Any)"
        doc = obj.__doc__ or ""
        # Escape triple quotes
        doc = doc.replace('"""', '\\"\\"\\"')
        lines.append(f"def {name}{sig} -> Any:")
        # Add docstring with indentation
        lines.append('    """' + doc.replace("\n", "\n    ") + '"""')
    else:
        # For non-functions, just annotate as Any
        lines.append(f"{name}: Any")

# Write the .pyi
TOOLS_PYI.write_text("\n".join(lines) + "\n")
print(f"Generated {TOOLS_PYI}")