import inspect
from pathlib import Path

# Import the modules explicitly — avoids relative import issues
import valency_anndata.tools as tools
import valency_anndata.preprocessing as pp
import valency_anndata.viz as viz

FILES = [
    (tools, Path("src/valency_anndata/tools/__init__.py")),
    (pp,    Path("src/valency_anndata/preprocessing/__init__.py")),
    (viz,   Path("src/valency_anndata/viz/__init__.py")),
]

for module, src_path in FILES:
    pyi_path = src_path.with_suffix(".pyi")
    exports = getattr(module, "__all__", [])

    lines = [
        "# ------------------------------------------------------",
        "# THIS FILE IS AUTO-GENERATED BY scripts/generate_ide_docstring_hints.py",
        f"# Source module: {src_path}",
        "# DO NOT EDIT MANUALLY",
        "# ------------------------------------------------------",
        "",
        "from typing import Any",
        "",
        f"__all__ = {exports!r}",
        "",
    ]

    for name in exports:
        obj = getattr(module, name, None)
        if obj is None:
            lines.append(f"{name}: Any")
            continue

        if inspect.isfunction(obj) or inspect.isbuiltin(obj):
            try:
                sig = str(inspect.signature(obj))
            except ValueError:
                sig = "(*args: Any, **kwargs: Any)"
            doc = obj.__doc__ or ""
            doc = doc.replace('"""', '\\"\\"\\"')
            lines.append(f"def {name}{sig} -> Any:")
            lines.append('    """' + doc.replace("\n", "\n    ") + '"""')
        else:
            lines.append(f"{name}: Any")

    pyi_path.write_text("\n".join(lines) + "\n")
    print(f"Generated {pyi_path}")
